branches:
  only:
  - master

pull_requests:
  do_not_increment_build_number: true

skip_non_tags: true
test: off
image: Visual Studio 2017

environment:
  CIBW_SKIP: cp27-* cp34-* cp35-*
  CIBW_BUILD_VERBOSITY: 3
  BUILD_OUTPUT_PATH: wheelhouse
  TWINE_USERNAME: cher-nov
  TWINE_PASSWORD:
    secure: hO+NR4mHqJGS/q3EBSvAgw==

install: |
  git submodule update --init --recursive
  choco install -y swig
  pip install twine cibuildwheel

before_build: >
  IF DEFINED CI_TEST_LAUNCH
  SET "PYPI_SETUP_VERSION_SUFFIX=dev999%APPVEYOR_BUILD_ID%";

build_script: |
  cibuildwheel --output-dir "%BUILD_OUTPUT_PATH%"

before_deploy: >
  IF DEFINED CI_TEST_LAUNCH
  SET "TWINE_REPOSITORY_URL=https://test.pypi.org/legacy/";

deploy_script: |
  twine upload --skip-existing "%BUILD_OUTPUT_PATH%/*.whl"

artifacts:
- path: "%BUILD_OUTPUT_PATH%/*.whl"
